name: Windows build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Build BELLE
        run: |
          cd .\belle
          cargo build --release

      - name: Build the BELLE-assembler
        run: |
          cd .\basm
          cargo build --release

      - name: Install dependencies (make, gcc) on Windows
        run: |
          choco install make
          choco install mingw
          $env:PATH += ";C:\tools\mingw\bin"

      - name: Build the BELLE-disassembler
        run: |
          cd .\bdump
          make

      - name: Test build script (Windows)
        run: .\build.ps1 -n

      - name: Test install script (Windows)
        run: .\install.ps1
